// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXEe2yyFKXoKtspW5tuUiWZn0qXfew1js',
    appId: '1:670990965256:web:8d46b5a7c9252b3ecdcfbd',
    messagingSenderId: '670990965256',
    projectId: 'eventcatcher-2ce7d',
    authDomain: 'eventcatcher-2ce7d.firebaseapp.com',
    storageBucket: 'eventcatcher-2ce7d.firebasestorage.app',
    measurementId: 'G-P2N7LDJM9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-LCToQjnoq73XYPY06aCS2l8v8qqeOGQ',
    appId: '1:670990965256:android:932d20dd4c1a3ed3cdcfbd',
    messagingSenderId: '670990965256',
    projectId: 'eventcatcher-2ce7d',
    storageBucket: 'eventcatcher-2ce7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqCyRzQGDrGYMCFB6ZRt5vrkmEIs_74bE',
    appId: '1:670990965256:ios:61fde2d66789200fcdcfbd',
    messagingSenderId: '670990965256',
    projectId: 'eventcatcher-2ce7d',
    storageBucket: 'eventcatcher-2ce7d.firebasestorage.app',
    iosBundleId: 'com.example.eventcatcher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqCyRzQGDrGYMCFB6ZRt5vrkmEIs_74bE',
    appId: '1:670990965256:ios:61fde2d66789200fcdcfbd',
    messagingSenderId: '670990965256',
    projectId: 'eventcatcher-2ce7d',
    storageBucket: 'eventcatcher-2ce7d.firebasestorage.app',
    iosBundleId: 'com.example.eventcatcher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXEe2yyFKXoKtspW5tuUiWZn0qXfew1js',
    appId: '1:670990965256:web:d52c127bdd1c108fcdcfbd',
    messagingSenderId: '670990965256',
    projectId: 'eventcatcher-2ce7d',
    authDomain: 'eventcatcher-2ce7d.firebaseapp.com',
    storageBucket: 'eventcatcher-2ce7d.firebasestorage.app',
    measurementId: 'G-D7JM5J4V9P',
  );
}
